### ISSUE TITLE
Alert until user interacts

### ISSUE THREAD

**Issue by oli-obk** [nfdz/tomatito#1]
I often don't notice that my phone vibrates. It would be great if there were a setting that made it vibrate until I interact with it.

**Comment by nfdz** [comment]
Thanks for the feedback,
I want to keep this version of the app as it is for educational purposes but I am going to prepare a newer and updated fork with all your recommendations. Stay tuned :) 
Cheers

**Comment by nfdz** [comment]
Finally, we have finished the development of a new improved app with this and more user recommendations, hope you like it: **Tomatime**
https://github.com/nfdz/tomatime
https://play.google.com/store/apps/details?id=io.github.nfdz.tomatime
Cheers
